NodeCAN:
  SvetlaZadne:
      id: 5
      DigOUT:
        svetloStena: { addr: [ 0x116, 0, 0 ], pin: PE0 }
        svetloStol: { addr: [ 0x116, 0, 1 ], pin: PE1 }
        svetloObyvka: { addr: [ 0x116, 0, 2 ], pin: PE2 }
        svetloChodbicka: { addr: [ 0x116, 0, 3 ], pin: PE3 }
        svetloKupelna: { addr: [ 0x116, 0, 4 ], pin: PE4 }
        svetloSpalna: { addr: [ 0x116, 0, 5 ], pin: PE5 }
      DigIN:
        buttonChodbickaLU: { addr: [ 0x120, 0, 0 ], pin: PA7 }
        buttonChodbickaLD: { addr: [ 0x120, 0, 1 ], pin: PC7 }
        buttonChodbickaRU: { addr: [ 0x120, 0, 2 ], pin: PA6 }
        buttonChodbickaRD: { addr: [ 0x120, 0, 3 ], pin: PG2 }
  SvetlaPredne:
      id: 2
      DigOUT:
        svetloKuchyna: { addr: [ 0x115, 0, 0 ], pin: PE0 }
        svetloIzba: { addr: [ 0x115, 0, 1 ], pin: PE1 }
        svetloWc: { addr: [ 0x115, 0, 2 ], pin: PE2 }
        svetloPavlac: { addr: [ 0x115, 0, 3 ], pin: PE3 }
  Zadverie:
      id: 6
      DigIN:
        zvoncek: { addr: [ 0x111, 0, 0 ], pin: PG0 }
        buttonZadverieLU: { addr: [ 0x111, 0, 1 ], pin: PC2 }
        buttonZadverieLD: { addr: [ 0x111, 0, 2 ], pin: PG2 }
        buttonZadverieRU: { addr: [ 0x111, 0, 3 ], pin: PC4 }
        buttonZadverieRD: { addr: [ 0x111, 0, 4 ], pin: PC6 }
        buttonKuchyna1LU: { addr: [ 0x111, 0, 5 ], pin: PD4 }
        buttonKuchyna1LD: { addr: [ 0x111, 0, 6 ], pin: PD2 }
        buttonKuchyna1RU: { addr: [ 0x111, 0, 7 ], pin: PC1 }
        buttonKuchyna1RD: { addr: [ 0x111, 1, 0 ], pin: PG1 }
        buttonIzbaU: { addr: [ 0x111, 1, 1 ], pin: PA4 }
        buttonIzbaD: { addr: [ 0x111, 1, 2 ], pin: PA6 }
      DigOUT:
        brana: { addr: [ 0x112, 0, 0 ], pin: PA2 }
      OwT:
        tIzba: { addr: [ 0x113, 0 ], owRomCode: 287f03780c0000e3 }
        tZadverie: { addr: [ 0x113, 2 ], owRomCode: 282cdf780c0000eb }
  Kupelka:
      id: 4
      OwT:
        tVodaKupelka: { addr: [ 0x119, 0 ], owRomCode: 28d50a0a06000046 }
        tPodlahovka: { addr: [ 0x119, 2 ], owRomCode: 287fc80a06000074, type: DS18S20}
        tSpalna: { addr: [ 0x119, 4 ], owRomCode: 28469e780c0000c3 }
      #SensorionCO2: { addr: 0x11A }
      #Vlhkomer: { addr: 0x11B }
  Spalna:
    id: 7
    DigIN:
      buttonSpalnaU: { addr: [ 0x118, 0, 0 ], pin: PC7 }
      buttonSpalnaD: { addr: [ 0x118, 0, 1 ], pin: PA7 }
  KupelnaVypinac:
      id: 3
      DigIN:
        buttonKupelna1U: { addr: [ 0x117, 0, 0 ], pin: PG2 }
        buttonKupelna1D: { addr: [ 0x117, 0, 1 ], pin: PA7 }
        buttonKupelna2U: { addr: [ 0x117, 0, 2 ], pin: PA6 }
        buttonKupelna2D: { addr: [ 0x117, 0, 3 ], pin: PC7 }

BBOw:
  tBoiler: { owRomCode : 284b7a0a06000089 }
  tRecir: { owRomCode : 28625008060000eb }
  tPavlac : { owRomCode : 28bf6f0a06000089 }
  tretKupelna: { owRomCode : 28aa97e33b14013c }
  tretKupelnaP: { owRomCode : 28a5db780c000088}
  tretPodlaha: { owRomCode : 28362709060000aa }
  tretSpalna1: { owRomCode : 28086d780c00004d}
  tretSpalna2: { owRomCode : 28ffab160d00002a }
  tretObyvka1: { owRomCode : 2831fd770c00001b}
  tretObyvka2: { owRomCode : 28de47780c00007e}
  tretIzba: { owRomCode : 28a3c0780c000036 }
  tretKuchyna: { owRomCode : 28c440780c0000bb}
  tObyvka: { owRomCode : 283a39790c0000cb}

    # SCL P9.19 i2c2_scl
    # SDA P9.20 i2c2_sda

    # CANRX P9.24 dcan1_rx
    # CANTX P9.26 dcan1_tx
    # CANPWR P9.28 gpio3_17
    
    # OWIN P9.27 pru0_r31_in5
    # OWOUT P9.29 pru0_r30_out1
    # OWSPWR P9.31 pru0_r30_out0
    # PUMPA P9.25
    # IMPELM p9.23
    # IMPVM p9.21
    
    # OTIN pru0_in14 P8_16
    # OTOUT pru0_out14 P8_12

#   1. žltý - +24V
#   2. čierny - GND
#   3. červený - CANH
#   4. biely - CANL

# GpioTest passed: 3,5,10,4,7,6,2
