#!/bin/bash

set -e

cd `dirname $0`
IPADDR=`./get-current`
[[ -n $IPADDR ]]
TMPF=/run/tmp/ip-addr-byt.txt
echo `date` check >> /tmp/check-script
if [[ -f $TMPF ]] && [[ $(<$TMPF) == $IPADDR ]]; then
	exit
fi

ping -c1 $IPADDR
./push $IPADDR
echo $IPADDR > $TMPF
